backend:
  name: git-gateway
  branch: main
  repo: tlsager/not-made-by-robots # Branch to update (optional; defaults to master)

media_folder: assets/img
public_folder: /img

locale: "de"

i18n:
  # Required and can be one of multiple_folders, multiple_files or single_file
  # multiple_folders - persists files in `<folder>/<locale>/<slug>.<extension>`
  # multiple_files - persists files in `<folder>/<slug>.<locale>.<extension>`
  # single_file - persists a single file in `<folder>/<slug>.<extension>`
  structure: multiple_folders

  # Required - a list of locales to show in the editor UI
  locales: [en, de]

  # Optional, defaults to the first item in locales.
  # The locale to be used for fields validation and as a baseline for the entry.
  default_locale: en

media_library:
  name: cloudinary
  config:
    cloud_name: dt5cqs0lv
    api_key: 347794518196229

collections:
  - name: "tutorial"
    label: "Tutorial"
    folder: "content/tutorial"
    format: "frontmatter"
    create: true
    slug: "{{slug}}"
    preview_path: "tutorial/{{slug}}"
    i18n: true
    editor:
      preview: false
    fields:
      - { label: "Title", name: "title", widget: "string", i18n: true }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - {
          label: "Description",
          name: "description",
          widget: "string",
          i18n: true,
        }
      - { label: "Preview", name: "preview", widget: "string", i18n: true }
      - { label: "Body", name: "body", widget: "markdown", i18n: true }
      - { label: "Image", name: "image", widget: "image" }
      - { label: "Video", name: "video", widget: "image" }
      - {
          label: "Wissen",
          name: "wissen_link",
          widget: "list",
          required: false,
        }
      - {
          label: "Level",
          name: "level",
          widget: "select",
          options:
            [
              "tutorial",
              "wissen",
              "theory",
              "low-code",
              "no-code",
              "high-code",
              "free",
              "premium",
              "kostenlos",
              "kostenpflichtig",
            ],
          i18n: true,
          multiple: true,
        }
  - name: "wissen"
    label: "Wissen"
    folder: "content/wissen"
    format: "frontmatter"
    create: true
    slug: "{{slug}}"
    preview_path: "wissen/{{slug}}"
    i18n: true
    editor:
      preview: false
    fields:
      - { label: "Title", name: "title", widget: "string", i18n: true }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - {
          label: "Description",
          name: "description",
          widget: "string",
          i18n: true,
        }
      - { label: "Body", name: "body", widget: "markdown", i18n: true }
      - { label: "Image", name: "image", widget: "image" }
      - {
          label: "Tutorial",
          name: "tutorial_link",
          widget: "list",
          requiered: false,
        }
      - {
          label: "Level",
          name: "level",
          widget: "select",
          options:
            [
              "tutorial",
              "wissen",
              "theory",
              "low-code",
              "no-code",
              "high-code",
              "free",
              "premium",
              "kostenlos",
              "kostenpflichtig",
            ],
          multiple: true,
        }
  - name: "ressourcen"
    label: "Ressourcen"
    folder: "content/ressourcen"
    format: "frontmatter"
    create: true
    slug: "{{slug}}"
    preview_path: "ressourcen/{{slug}}"
    i18n: true
    editor:
      preview: false
    fields:
      - { label: "Title", name: "title", widget: "string", i18n: true }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - {
          label: "Description",
          name: "description",
          widget: "string",
          i18n: true,
        }
      - { label: "Image", name: "image", widget: "image" }
      - { label: "Link", name: "link", widget: "string" }
      - {
          label: "Level",
          name: "level",
          widget: "select",
          i18n: true,
          options:
            [
              "person",
              "tutorial",
              "wissen",
              "theory",
              "low-code",
              "no-code",
              "high-code",
              "free",
              "premium",
              "kostenlos",
              "kostenpflichtig",
            ],
          multiple: true,
        }
